"""
similarity_network.py — Multi-attribute employee similarity graph generator.

Replaces the manager-hierarchy tree (org_hierarchy.py, untouched, still
live and reconnectable) as the data source for /dashboard/org-network.

DISTANCE MODEL
--------------
Three weighted buckets, each normalized to [0, 1] before weighting:

  Hierarchical (weight 0.6):
    - manager_id match     (from data/org_hierarchy.json)
    - department match
    - project match        (synthetic, see synthetic_attributes.py)

  Flat categorical (weight 0.2):
    - gender match
    - performance_tier match (High = manager rating in {1,2}, Low = {3,4})

  Continuous, normalized (weight 0.2):
    - age (min-max normalized within department)
    - prob_of_leaving / General_Risk_Score (already 0-100, normalized to 0-1)

MISSING PERFORMANCE DATA
------------------------
If an employee has no row in `performance_ratings` (table may not be seeded
yet — see server.py memory notes), the performance_tier dimension is DROPPED
for that employee's distance calculations and their remaining per-bucket
weights are rescaled to sum to 1.0 (reweight-and-exclude, not a neutral
midpoint fill). This is asymmetric: employee A with performance data and
employee B without will have A's fields subset to compute distance(A, B).

OUTPUT
------
Per-department JSON: data/similarity_network_{department_slug}.json
Schema:
{
  "department": "Sales",
  "nodes": [ {id, department, job_role, job_level, gender, age,
              risk_score, performance_tier, manager_id, project, is_active}, ... ],
  "edges": [ {source, target, weight}, ... ]   // weight = 1 - distance (similarity)
}

k-NN: k = min(32, ceil(dept_size * 0.1)), floor 3.
"""
import json
import math
import os
import sqlite3
from typing import Dict, List, Optional, Tuple

import numpy as np
import pandas as pd

from pipeline.config import OLAP_PATH, DATA_DIR

ORG_HIERARCHY_PATH = os.path.join(DATA_DIR, "org_hierarchy.json")

# Bucket weights (locked spec)
W_HIERARCHICAL = 0.6
W_CATEGORICAL = 0.2
W_CONTINUOUS = 0.2

# Sub-weights within hierarchical bucket (equal split, per your "equal within
# categorical" instruction extended here since you didn't override it)
HIER_SUBWEIGHTS = {"manager": 1 / 3, "department": 1 / 3, "project": 1 / 3}
CAT_SUBWEIGHTS = {"gender": 0.5, "performance_tier": 0.5}
CONT_SUBWEIGHTS = {"age": 0.5, "risk_score": 0.5}

K_MAX = 20
K_FLOOR = 3


def load_employee_cohort() -> pd.DataFrame:
    """Pull active employees + risk scores + (if present) manager ratings."""
    conn = sqlite3.connect(OLAP_PATH)
    query = """
    SELECT
        v.EmployeeId, v.Department, v.JobRole, v.JobLevel, v.Age, v.Gender, v.Project,
        r.General_Risk_Score
    FROM v_ml_features v
    LEFT JOIN flight_risk_scores r ON v.EmployeeId = r.EmployeeId
    """
    try:
        df = pd.read_sql(query, conn)
    except pd.io.sql.DatabaseError as e:
        conn.close()
        raise RuntimeError(
            "v_ml_features query failed -- likely missing Project column. "
            "Apply pipeline/etl_patch.md and re-run etl.py first."
        ) from e

    # Manager-entered performance rating: table may not exist yet.
    try:
        perf_df = pd.read_sql(
            "SELECT EmployeeId, rating FROM performance_ratings", conn
        )
        perf_map = dict(zip(perf_df["EmployeeId"], perf_df["rating"]))
    except Exception:
        perf_map = {}  # table not seeded yet -- fallback: everyone "missing"

    conn.close()

    df["performance_rating_raw"] = df["EmployeeId"].map(perf_map)
    df["performance_tier"] = df["performance_rating_raw"].apply(
        lambda r: None if pd.isna(r) else ("High" if r in (1, 2) else "Low")
    )
    df["has_performance_data"] = df["performance_tier"].notna()

    return df


def load_manager_lookup() -> Dict[str, str]:
    """manager_id per EmployeeId from the synthetic org hierarchy JSON.
    NOTE: this file is regenerated by org_hierarchy.py on the nightly ETL
    trigger (simulator_actions.trigger_nightly_etl_ml). Manager assignments
    -- and therefore hierarchical-distance clusters -- can shift between
    runs even when no real employee attribute changed. This is a known
    property of the synthetic-hierarchy design, not a bug in this module."""
    if not os.path.exists(ORG_HIERARCHY_PATH):
        return {}
    with open(ORG_HIERARCHY_PATH, "r") as f:
        data = json.load(f)
    return {n["id"]: n.get("manager_id", "") for n in data.get("nodes", [])}


def _normalize_column(series: pd.Series) -> pd.Series:
    lo, hi = series.min(), series.max()
    if hi - lo == 0:
        return series.apply(lambda x: 0.5)
    return (series - lo) / (hi - lo)


def compute_distance(
    a: pd.Series, b: pd.Series, manager_lookup: Dict[str, str]
) -> float:
    """
    Composite weighted distance between two employees. Returns value in
    roughly [0, 1] (exact bound depends on continuous normalization range).

    Reweight-and-exclude: if either employee lacks performance_tier data,
    the categorical bucket's performance_tier sub-dimension is dropped and
    that sub-weight is redistributed across the remaining categorical
    sub-dimensions (here: gender absorbs it, since it's the only one left).
    """
    # --- Hierarchical bucket ---
    manager_a = manager_lookup.get(a["EmployeeId"], "")
    manager_b = manager_lookup.get(b["EmployeeId"], "")
    d_manager = 0.0 if manager_a == manager_b and manager_a != "" else 1.0
    d_department = 0.0 if a["Department"] == b["Department"] else 1.0
    d_project = 0.0 if a["Project"] == b["Project"] else 1.0

    hier_dist = (
        HIER_SUBWEIGHTS["manager"] * d_manager
        + HIER_SUBWEIGHTS["department"] * d_department
        + HIER_SUBWEIGHTS["project"] * d_project
    )

    # --- Categorical bucket (with reweight-and-exclude for performance) ---
    d_gender = 0.0 if a["Gender"] == b["Gender"] else 1.0
    both_have_perf = a["has_performance_data"] and b["has_performance_data"]

    if both_have_perf:
        d_perf = 0.0 if a["performance_tier"] == b["performance_tier"] else 1.0
        cat_dist = (
            CAT_SUBWEIGHTS["gender"] * d_gender
            + CAT_SUBWEIGHTS["performance_tier"] * d_perf
        )
    else:
        # Exclude performance dimension, rescale gender to carry full weight
        cat_dist = 1.0 * d_gender

    # --- Continuous bucket ---
    d_age = abs(a["age_norm"] - b["age_norm"])
    d_risk = abs(a["risk_norm"] - b["risk_norm"])
    cont_dist = (
        CONT_SUBWEIGHTS["age"] * d_age + CONT_SUBWEIGHTS["risk_score"] * d_risk
    )

    return (
        W_HIERARCHICAL * hier_dist
        + W_CATEGORICAL * cat_dist
        + W_CONTINUOUS * cont_dist
    )


def build_department_graph(
    df_dept: pd.DataFrame, manager_lookup: Dict[str, str]
) -> Tuple[List[dict], List[dict]]:
    df_dept = df_dept.copy().reset_index(drop=True)
    df_dept["age_norm"] = _normalize_column(df_dept["Age"])
    df_dept["risk_norm"] = _normalize_column(df_dept["General_Risk_Score"].fillna(0))

    n = len(df_dept)
    k = max(K_FLOOR, min(K_MAX, math.ceil(n * 0.1)))

    # Full pairwise distance matrix (department-scoped, so this is bounded:
    # max department size here is R&D at 975 -> ~950k pairs, acceptable
    # for a one-time server-side batch job, NOT for live/on-request compute)
    dist_matrix = np.zeros((n, n))
    for i in range(n):
        for j in range(i + 1, n):
            d = compute_distance(df_dept.iloc[i], df_dept.iloc[j], manager_lookup)
            dist_matrix[i, j] = d
            dist_matrix[j, i] = d

    edges = []
    seen_pairs = set()
    for i in range(n):
        neighbor_order = np.argsort(dist_matrix[i])
        neighbor_order = neighbor_order[neighbor_order != i][:k]
        for j in neighbor_order:
            pair = tuple(sorted((i, int(j))))
            if pair in seen_pairs:
                continue
            seen_pairs.add(pair)
            edges.append(
                {
                    "source": df_dept.iloc[pair[0]]["EmployeeId"],
                    "target": df_dept.iloc[pair[1]]["EmployeeId"],
                    "weight": round(1.0 - dist_matrix[pair[0], pair[1]], 4),
                }
            )

    nodes = []
    for _, row in df_dept.iterrows():
        nodes.append(
            {
                "id": row["EmployeeId"],
                "department": row["Department"],
                "job_role": row["JobRole"],
                "job_level": row["JobLevel"],
                "gender": row["Gender"],
                "age": int(row["Age"]),
                "project": row["Project"],
                "manager_id": manager_lookup.get(row["EmployeeId"], ""),
                "performance_tier": row["performance_tier"],
                "risk_score": float(row["General_Risk_Score"] or 0),
            }
        )

    return nodes, edges


def generate_all_department_graphs(output_dir: Optional[str] = None) -> List[str]:
    output_dir = output_dir or DATA_DIR
    df = load_employee_cohort()
    manager_lookup = load_manager_lookup()

    written = []
    for dept in df["Department"].dropna().unique():
        df_dept = df[df["Department"] == dept]
        nodes, edges = build_department_graph(df_dept, manager_lookup)

        slug = dept.replace(" ", "_").replace("&", "and")
        out_path = os.path.join(output_dir, f"similarity_network_{slug}.json")
        with open(out_path, "w") as f:
            json.dump({"department": dept, "nodes": nodes, "edges": edges}, f, indent=2)
        written.append(out_path)
        print(f"[+] {dept}: {len(nodes)} nodes, {len(edges)} edges -> {out_path}")

    return written


if __name__ == "__main__":
    generate_all_department_graphs()
